// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://teuixcvmdckpyyyrjfqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRldWl4Y3ZtZGNrcHl5eXJqZnFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MjUzMDYsImV4cCI6MjA2MjQwMTMwNn0.uJWD55AlySYSt7jSXfBNmoz9caJz2CwM1MdB5FeYFCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);